### ISSUE TITLE
preStringTyped: Missing parametr `arrayPos`

### ISSUE THREAD

**Issue by cibulka** [mattboldt/typed.js#538] opened 2023-03-17 19:19 UTC
### Description

The new version of the library should pass 2 parameters to `preStringTyped` callback: `arrayPos` and `self`.

The current version 2.0.132 passes only `self` however.

### Demo

Unfortunately I can not fork [the fiddle](https://jsfiddle.net/mattboldt/1xs3LLmL/) - it seems that there is still [the older version v2.0.12 included](https://rawgit.com/mattboldt/typed.js/master/lib/typed.js), where the callback works as documented.

### Steps to Reproduce

1. Install 2.0.132 version of the library
2. Call the Typed.js library with `preStringTyped` callback and console.log the parameters

```
var typed = new Typed("#typed", {
  strings: ['Some <i>strings</i> with', 'Some <strong>HTML</strong>', 'Chars &times; &copy;'],
  preStringTyped: console.log
});
```

**Expected behavior:** [What you expect to happen]

See 2 parameters, `arrayPos: number` and `self: HTMLSpanElement`, as documented.

**Actual behavior:** [What actually happens]

Only "self" parameter is passed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Additional Information

Downgrading to v2.0.12 fixes the problem for now. :) Thanks for an awesome library!

**Comment by mattboldt** [comment] 2023-03-26 02:48
Thanks for the detailed report! I just updated the jsfiddle to use the newest version, but unfortunately I cannot reproduce what you're describing. Here's a fork logging the args of that method: https://jsfiddle.net/mattboldt/es9pfyhz/1/

**Comment by mattboldt** [comment] 2023-04-01 19:13
Closing this, but let me know if you're still running into this issue!

**Closed by mattboldt** 2023-04-01 19:13 UTC

**Comment by cibulka** [comment] 2023-04-02 12:11
Hey Matt, sorry for the delay with my answer! Everything seems to work alright indeed, it seems that my issue was somewhere else. Thanks again!
