### ISSUE TITLE
Word per word typing

### ISSUE THREAD

**Issue by arvi** [mattboldt/typed.js#270] opened 2017-07-06 08:56 UTC
### Description

Word per word typing effect

**Expected behavior:** 
Sentences are typed in a word per word basis

**Actual behavior:** 
Sentences are typed in a letter basis

I would like to know the possibility of this.

**Comment by mattboldt** [comment] 2017-07-06 15:22
Dupe of https://github.com/mattboldt/typed.js/issues/215

**Closed by mattboldt** 2017-07-06 15:22 UTC
