### ISSUE TITLE
[Feature Request] Reactive strings

### ISSUE THREAD

**Issue by AndreaMinato** [mattboldt/typed.js#378] opened 2018-06-08 09:13 UTC
### Description
I want to use typed.js with vueJs to have some kind of reactivity on the strings.
The final goal is to use it with Firebase RealTime Database, so i would like to have the chance to add strings after the typed instance is created.

I have tried like this:
```javascript
sentences.push(sentence);
typed.strings = sentences;
```
And like this
```javascript
typed.strings.push(sentence);
```
But I always end up with this error
`
Uncaught TypeError: Cannot read property 'substr' of undefined
    at HTMLParser.typeHtmlChars (VM69 typed.js:978)
    at VM69 typed.js:228
`

### Demo
I have a demo of my problem in Codepen, I tried to make it more similar to the jsFiddle fork you request.

https://codepen.io/andreaminato/pen/eKBGzX?editors=1010

### Steps to Reproduce
1. Open console.log
1. Try to add a sentence

**Expected behavior:** Just use the new strings set

**Actual behavior:** It stops with that error

**Reproduces how often:** All time

**Comment by mattboldt** [comment] 2018-06-14 15:47
This may be a dupe of https://github.com/mattboldt/typed.js/issues/283

Please check and re-open if necessary, thanks!

**Closed by mattboldt** 2018-06-14 15:47 UTC

**Comment by AndreaMinato** [comment] 2018-06-14 16:00
Just keep this closed for now, indeed the issue is quite similar, I will investigate deeper and in case update the #283
